---

- name: Install required system packages
  become: true
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python3-pip
      - python3-setuptools
      - acl
    state: latest

- name: Add Docker repository
  become: true
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Install Docker CE and Docker Compose
  become: true
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- name: Ensure docker service is started and enabled
  become: true
  service:
    name: docker
    state: started
    enabled: true

- name: Create group
  become: true
  group:
    name: "{{ group }}"
    state: present

- name: Create user
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    uid: 1040
    group: "{{ group }}"

- name: Creates home directory
  become: true
  file:
    path: "/home/{{ user }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0744'

- name: Create Dirs
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - "{{ registry_path }}"
    - "{{ registry_data }}"

- name: Copy docker compose file
  become: true
  template:
    src: "./templates/docker-compose.yaml.j2"
    dest: "{{ registry_path }}/docker-compose.yaml"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644

- name: Start docker compose
  become: true
  become_user: "{{ user }}"
  shell: docker compose up -d
  args:
    chdir: "{{ registry_path }}"

- name: Get docker containers
  become: true
  become_user: "{{ user }}"
  shell: docker ps -a

- name: Check if docker-registry is listening on port 5000
  ansible.builtin.wait_for: 
    port: 5000
    state: started
    timeout: 30